version: "2.1"
services:
  ddclient:
    image: lscr.io/linuxserver/ddclient:v3.10.0-ls126
    container_name: ddclient
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/divam/docker-services/ddns:/config
    network_mode: host
    restart: unless-stopped
